sudo: false
language: python

python:
  - "3.6"

install:
  - pip install -e .
  - pip install py-moneyed
  - pip install python-dateutil
  - pip install coverage
  - pip install coveralls

script: coverage run --source=mortgagekit setup.py test

after_success:
  coveralls
